### ISSUE TITLE
API returns 500 in Prod

### ISSUE THREAD

**Issue by qWeX23** [qWeX23/FireGaugeAlert#6]
Someone did not test and now the Azure function does not return anything but 500 in prod.

**Comment by wpe19d** [comment]
Ask Ronald what he did

**Comment by qWeX23** [comment]
[looks like its not reading the connection string](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227c2ca768-439c-41b6-9791-ff35b2ccbf7d%22%2C%22ResourceGroup%22%3A%22firealert%22%2C%22ResourceProvider%22%3A%22microsoft.insights%22%2C%22ResourceType%22%3A%22components%22%2C%22Name%22%3A%22firealertappinsights%22%7D/DataModel/%7B%22eventId%22%3A%22cbd8dfe9-d5c0-11eb-b561-281878ec83d3%22%2C%22timestamp%22%3A%222021-06-25T14%3A22%3A06.255Z%22%2C%22cacheId%22%3A%2283411b26-7a3d-4c1e-a8df-c84bac6331db%22%2C%22eventTable%22%3A%22requests%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A3600000%2C%22endTime%22%3A%222021-06-25T14%3A27%3A00.000Z%22%2C%22createdTime%22%3A%222021-06-25T14%3A27%3A25.000Z%22%2C%22isInitialTime%22%3Afalse%2C%22grain%22%3A1%2C%22useDashboardTimeRange%22%3Afalse%7D%7D )

**Comment by qWeX23** [comment]
I fixed the connection string (it had quotes in the setting)`

[ but now there is an issue connecting to mongo](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227c2ca768-439c-41b6-9791-ff35b2ccbf7d%22%2C%22ResourceGroup%22%3A%22firealert%22%2C%22ResourceProvider%22%3A%22microsoft.insights%22%2C%22ResourceType%22%3A%22components%22%2C%22Name%22%3A%22firealertappinsights%22%7D/DataModel/%7B%22eventId%22%3A%2236e94cb0-d5c2-11eb-b561-281878eca4e2%22%2C%22timestamp%22%3A%222021-06-25T14%3A32%3A19.66Z%22%2C%22cacheId%22%3A%22472b2e4d-7174-4277-976d-2ed059103d4c%22%2C%22eventTable%22%3A%22requests%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A3600000%2C%22endTime%22%3A%222021-06-25T14%3A39%3A00.000Z%22%2C%22createdTime%22%3A%222021-06-25T14%3A39%3A01.000Z%22%2C%22isInitialTime%22%3Afalse%2C%22grain%22%3A1%2C%22useDashboardTimeRange%22%3Afalse%7D%7D)

**Comment by qWeX23** [comment]
I changed the config in the DB to allow any IP address. seems to be working now 
![image](https://user-images.githubusercontent.com/11063838/123442461-83ed9f00-d59a-11eb-8f36-8147524359a2.png)
